// Mocks generated by Mockito 5.4.3 from annotations
// in flutter_training/test/src/feature/weather_forecast/data/weather_forecast_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:flutter_training/src/features/weather_forecast/domain/entities/entities.dart'
    as _i2;
import 'package:flutter_training/src/plugins/yumemi_weather/yumemi_weather_remote_data_source.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeWeatherInformation_0 extends _i1.SmartFake
    implements _i2.WeatherInformation {
  _FakeWeatherInformation_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [YumemiWeatherRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockYumemiWeatherRemoteDataSource extends _i1.Mock
    implements _i3.YumemiWeatherRemoteDataSource {
  @override
  _i2.WeatherInformation fetchWeatherForecast(
          {required _i2.WeatherForecastRequest? weatherForecastRequest}) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchWeatherForecast,
          [],
          {#weatherForecastRequest: weatherForecastRequest},
        ),
        returnValue: _FakeWeatherInformation_0(
          this,
          Invocation.method(
            #fetchWeatherForecast,
            [],
            {#weatherForecastRequest: weatherForecastRequest},
          ),
        ),
        returnValueForMissingStub: _FakeWeatherInformation_0(
          this,
          Invocation.method(
            #fetchWeatherForecast,
            [],
            {#weatherForecastRequest: weatherForecastRequest},
          ),
        ),
      ) as _i2.WeatherInformation);
}
